// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: seamless-point-ui

#include "../ui.h"

void ui_device_screen_init(void)
{
    ui_device = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_device, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_device, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_device, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel31 = lv_obj_create(ui_device);
    lv_obj_set_width(ui_Panel31, 345);
    lv_obj_set_height(ui_Panel31, 230);
    lv_obj_set_x(ui_Panel31, 6);
    lv_obj_set_y(ui_Panel31, -68);
    lv_obj_set_align(ui_Panel31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel31, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Panel31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel31, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volume_icon = lv_imagebutton_create(ui_device);
    lv_imagebutton_set_src(ui_volume_icon, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_on2_png, NULL);
    lv_imagebutton_set_src(ui_volume_icon, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_off2_png, NULL);
    lv_obj_set_width(ui_volume_icon, 47);
    lv_obj_set_height(ui_volume_icon, 40);
    lv_obj_set_x(ui_volume_icon, -2);
    lv_obj_set_y(ui_volume_icon, 6);
    lv_obj_set_align(ui_volume_icon, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_volume_icon, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_volume_icon, LV_SCROLLBAR_MODE_ACTIVE);

    ui_volume = lv_obj_create(ui_device);
    lv_obj_set_width(ui_volume, lv_pct(100));
    lv_obj_set_height(ui_volume, lv_pct(34));
    lv_obj_set_x(ui_volume, 0);
    lv_obj_set_y(ui_volume, 65);
    lv_obj_set_align(ui_volume, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_volume, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_volume, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_volume, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_volume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volume_slider = lv_slider_create(ui_volume);
    lv_slider_set_value(ui_volume_slider, 30, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_volume_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_volume_slider, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_volume_slider, lv_pct(70));
    lv_obj_set_height(ui_volume_slider, lv_pct(45));
    lv_obj_set_align(ui_volume_slider, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_volume_slider,
                       LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_volume_slider, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volume_slider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_volume_slider, lv_color_hex(0x969696), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volume_slider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_volume_slider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volume_slider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_volume_slider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_volume_slider,
                                                                                                    lv_obj_get_style_pad_right(ui_volume_slider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_status = lv_obj_create(ui_device);
    lv_obj_set_width(ui_status, lv_pct(100));
    lv_obj_set_height(ui_status, lv_pct(25));
    lv_obj_set_x(ui_status, 6);
    lv_obj_set_y(ui_status, -59);
    lv_obj_set_align(ui_status, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_status, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_status, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_status, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_device_status = lv_label_create(ui_status);
    lv_obj_set_width(ui_device_status, 111);
    lv_obj_set_height(ui_device_status, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_y(ui_device_status, 0);
    lv_obj_set_x(ui_device_status, lv_pct(10));
    lv_obj_set_align(ui_device_status, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_device_status, "JBL Speaker");
    lv_obj_remove_flag(ui_device_status,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_device_status, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_font(ui_device_status, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_status_control = lv_switch_create(ui_status);
    lv_obj_set_width(ui_status_control, 50);
    lv_obj_set_height(ui_status_control, 30);
    lv_obj_set_x(ui_status_control, -20);
    lv_obj_set_y(ui_status_control, 0);
    lv_obj_set_align(ui_status_control, LV_ALIGN_RIGHT_MID);


    lv_obj_add_event_cb(ui_Panel31, ui_event_Panel31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_device, ui_event_device, LV_EVENT_ALL, NULL);

}
