// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: seamless-point-ui

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_idle
void ui_idle_screen_init(void);
lv_obj_t * ui_idle;
lv_obj_t * ui_connectivity;
lv_obj_t * ui_date;
lv_obj_t * ui_linux_time;
lv_obj_t * ui_linux_date;
lv_obj_t * ui_bt_icon;
lv_obj_t * ui_wifi_icon;
lv_obj_t * ui_devices;
void ui_event_device_0(lv_event_t * e);
lv_obj_t * ui_device_0;
lv_obj_t * ui_text_device_1;
void ui_event_device_2(lv_event_t * e);
lv_obj_t * ui_device_2;
lv_obj_t * ui_text_device_3;
lv_obj_t * ui_clients;
lv_obj_t * ui_connection_0;
lv_obj_t * ui_text_connection_0;
lv_obj_t * ui_connection_1;
lv_obj_t * ui_text_connection_1;
lv_obj_t * ui_connection_2;
lv_obj_t * ui_text_connection_2;


// SCREEN: ui_device
void ui_device_screen_init(void);
void ui_event_device(lv_event_t * e);
lv_obj_t * ui_device;
void ui_event_Panel31(lv_event_t * e);
lv_obj_t * ui_Panel31;
lv_obj_t * ui_volume_icon;
lv_obj_t * ui_volume;
lv_obj_t * ui_volume_slider;
lv_obj_t * ui_status;
lv_obj_t * ui_device_status;
lv_obj_t * ui_status_control;
lv_obj_t * ui____initial_actions0;
const lv_image_dsc_t * ui_imgset_bt[1] = {&ui_img_bt2_png};
const lv_image_dsc_t * ui_imgset_off[1] = {&ui_img_off2_png};
const lv_image_dsc_t * ui_imgset_on[1] = {&ui_img_on2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_device_0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_device, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_device_screen_init);
    }
}
void ui_event_device_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_device, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_device_screen_init);
    }
}
void ui_event_device(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_idle, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_idle_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_idle, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_idle_screen_init);
    }
}
void ui_event_Panel31(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_idle, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_idle_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_idle, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_idle_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_idle_screen_init();
    ui_device_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_idle);
}
